param([string]$Protoc = '', [switch]$Check)
. "$PSScriptRoot/Common.ps1"
$contractRoot = Join-Path $RepoRoot 'contracts/realtime'
$config = Get-Content "$contractRoot/codegen.json" -Raw | ConvertFrom-Json
$codes = Get-Content "$contractRoot/codes.json" -Raw | ConvertFrom-Json
if (!$Protoc) {
    $Protoc = Join-Path $RepoRoot 'socket-server/out/build/windows-x64/vcpkg_installed/x64-windows/tools/protobuf/protoc.exe'
}
if (!(Test-Path -LiteralPath $Protoc)) { throw 'Build the socket server first, or provide -Protoc.' }
$version = & $Protoc --version
if ($LASTEXITCODE -ne 0 -or $version -ne "libprotoc $($config.protocVersion)") {
    throw "Expected protoc $($config.protocVersion), got '$version'. Update codegen.json deliberately when upgrading."
}
$runtime = Join-Path $RepoRoot 'client/Assets/Plugins/Google.Protobuf/Google.Protobuf.dll'
if ((Get-FileHash $runtime -Algorithm SHA256).Hash.ToLowerInvariant() -ne $config.csharpRuntimeSha256 -or
    [Reflection.AssemblyName]::GetAssemblyName($runtime).Version.ToString() -ne $config.csharpRuntimeVersion) {
    throw 'The checked-in C# Protobuf runtime does not match codegen.json.'
}
foreach ($group in @($codes.messages, $codes.errors)) {
    if (@($group.PSObject.Properties).Count -eq 0) { throw 'Wire-code groups must not be empty.' }
    $values = @()
    foreach ($entry in $group.PSObject.Properties) {
        if ($entry.Name -notmatch '^[A-Za-z][A-Za-z0-9]*$' -or ($entry.Value -isnot [long] -and $entry.Value -isnot [int]) -or
            $entry.Value -lt 0 -or $entry.Value -gt 255 -or $values -contains $entry.Value) {
            throw "Invalid or duplicate wire code: $($entry.Name)."
        }
        $values += $entry.Value
    }
}
foreach ($response in $codes.responses.PSObject.Properties) {
    if (!$codes.messages.PSObject.Properties[$response.Name] -or !$codes.messages.PSObject.Properties[$response.Value]) {
        throw "Unknown response mapping: $($response.Name)."
    }
}
$tempRoot = Join-Path $RepoRoot ('.tools/protocol/' + [guid]::NewGuid().ToString('N'))
[IO.Directory]::CreateDirectory($tempRoot) | Out-Null
$protoArgs = @("--proto_path=$contractRoot/proto", "--csharp_out=$tempRoot")
$protoArgs += @($config.csharpSchemas | ForEach-Object { Join-Path "$contractRoot/proto" $_ })
Invoke-Checked $Protoc $protoArgs

$notice = '// Generated by tools/Generate-Protocol.ps1 from contracts/realtime/codes.json. Do not edit.'
$cppMessages = @($notice, '#ifndef ZPD_MESSAGECODE_HPP', '#define ZPD_MESSAGECODE_HPP', '', '#include <cstdint>', '', 'enum class MessageCode : std::uint8_t', '{')
$cppMessages += @($codes.messages.PSObject.Properties | ForEach-Object { "    $($_.Name) = $($_.Value)," })
$cppMessages += @('};', '', 'constexpr MessageCode ResponseCodeFor(MessageCode request) noexcept', '{', '    switch (request) {')
foreach ($entry in $codes.responses.PSObject.Properties) {
    $cppMessages += @("    case MessageCode::$($entry.Name):", "        return MessageCode::$($entry.Value);")
}
$cppMessages += @('    default:', '        return MessageCode::ErrorResponse;', '    }', '}', '', '#endif // ZPD_MESSAGECODE_HPP')
$cppErrors = @($notice, '#ifndef ZPD_ERRORCODE_HPP', '#define ZPD_ERRORCODE_HPP', '', '#include <cstdint>', '', 'enum class ErrorCode : std::uint8_t', '{')
$cppErrors += @($codes.errors.PSObject.Properties | ForEach-Object { "    $($_.Name) = $($_.Value)," })
$cppErrors += @('};', '', '#endif // ZPD_ERRORCODE_HPP')
$csharp = @($notice, 'namespace Zpd.Networking', '{', '    public static class MessageCode', '    {')
$csharp += @($codes.messages.PSObject.Properties | ForEach-Object { "        public const byte $($_.Name) = $($_.Value);" })
$csharp += @('    }', '', '    public static class ProtocolErrorCode', '    {')
$csharp += @($codes.errors.PSObject.Properties | ForEach-Object { "        public const byte $($_.Name) = $($_.Value);" })
$csharp += @('    }', '}')
$outputs = @{
    'socket-server/common/include/MessageCode.hpp' = $cppMessages -join "`n"
    'socket-server/common/include/ErrorCode.hpp' = $cppErrors -join "`n"
    'client/Assets/Scripts/Networking/Tcp/Generated/ProtocolCodes.cs' = $csharp -join "`n"
}
foreach ($file in Get-ChildItem $tempRoot -Filter '*.cs') {
    $outputs['client/Assets/Scripts/Networking/Tcp/Generated/' + $file.Name] = [IO.File]::ReadAllText($file.FullName)
}
foreach ($entry in $outputs.GetEnumerator()) {
    $path = Join-Path $RepoRoot $entry.Key
    $expected = $entry.Value.Replace("`r`n", "`n").TrimEnd() + "`n"
    if ($Check) {
        if (!(Test-Path $path) -or [IO.File]::ReadAllText($path).Replace("`r`n", "`n") -cne $expected) {
            throw "Generated file is stale: $($entry.Key). Run tools/Generate-Protocol.ps1."
        }
    } else { Write-Utf8File $path $expected }
}
Write-Host $(if ($Check) { 'Protocol generated files are current.' } else { 'Protocol generated files updated.' })
